### ISSUE TITLE
DeadLine

### ISSUE THREAD

**Issue by mikelovato** [hxxyy/air-conditioning-system#5]
* 今天我添加完了流程图,对docx也有些改,你们再修改一遍应该就可以交了
* 流程图全部在[~/doc/img/]()文件夹下,你们想修改使用[www.draw.io](www.draw.io)打开修改然后保存就可以了
* 你们对Issues有啥看法,我还觉得不错...

**Comment by hxxyy** [comment]
ddl是明晚12点前吗？
解决方案里是不是不用写接口定义？现在写上接口感觉有点早。

**Comment by mikelovato** [comment]
* 那就删了吧,反正不影响啥...
* ddl我不知道....
* 我觉得要是交的话,转为pdf再交吧,要不然老师万一字体不匹配打开乱码就完蛋了
> 我提交issues你们会收到邮箱提醒吗

**Comment by hxxyy** [comment]
嗯，转pdf再交，那我删了接口， 以后的文档里再加。

**Comment by hxxyy** [comment]
会有邮箱提醒，感觉挺方便的。

**Comment by mikelovato** [comment]
* 我觉得我们对uml图的理解还是有问题,老师的要求好像更接近类图....
* 我这周三考完数据库开始写命令行版的..大概到下周三或者是下周天写完..
* 有什么问题随时提,关于通信协议初步打算就按照群里的协议来写..
